# Generated by Django 5.2.4 on 2025-07-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtor', models.CharField(max_length=100, verbose_name='Автор')),
                ('composition', models.CharField(max_length=100, verbose_name='Композиция')),
                ('year', models.DateField(verbose_name='Дата произведения')),
            ],
        ),
    ]
